# Generated by Django 3.2 on 2021-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(default=True, verbose_name='性别'),
        ),
    ]
